#%RAML 1.0
  ---
  title: taskmanager API
  baseUri: http://api.e-bookmobile.com/{version}
  version: v1

  /users:
    /register:
      post:
        description: Creates a new user.
        responses:
              201:
                body:
                  application/json:
                    example: |
                      "data": [
                          {
                            "firstname": "Sion",
                            "lastname": "Williams",
                            "email": "some@email.com",
                            "password": "secret"
                          }
                          ]
              500:
                body:
                  application/json:
                    example: |
                      "data": [
                          {
                            "error": "Some Error",
                            "message": "Invalid User data",
                            "status": 500
                          }
                          ]
    /login:
      post:
        description: User logs in to the system, which returns a JWT if the login is successful.
        responses:
              201:
                body:
                  application/json:
                    example: |
                      "data": [
                          {
                            "user": "some@email.com",
                            "token": "550e8400e29b41d4a716446655440222"
                          }
                          ]

  /tasks:
    post:
      description: Creates a new task.
    get:
    /{id}:
      put:
        description: Updates an existing task with `taskId = {id}`.
      get:
        description: Get a single task with `taskId = {id}`.
      delete:
        description: Deletes an existing task with `taskId = {id}`.
    /users:
      /{id}
        get:
          description: Get all tasks associated with a user with `userId = {id}`.

  /notes:
    post:
      description: Create a new note against an existing task.
    get:
      description: Get all task notes.
    /{id}:
      put:
        description: Update an existing task note with `noteId = {id}`
      get:
        description: Get a single note with `noteId = {id}`
      delete:
        description: Delete an existing note for a given task with `noteId = {id}`
    /tasks:
      /{id}
        get:
          description: Gets all notes for a given `taskId = {id}`.
